### ISSUE TITLE
Please provide an option to use the "Listen Key" rather than the account login credentials.

### ISSUE THREAD

**Issue by YAMLcase** [ssapalski/plugin.audio.addict#1]
There are some users that will not feel comfortable entering their Google of Facebook account info for Premium authentication.  Please add a way to use the Listen Key instead.  This option can be found in "My Account" -> "Player Settings".  I have confirmed the key is the same for at lest di.fm and radiotunes.  Thank you!

**Comment by ssapalski** [comment]
I understand your point, Google/Facebook credentials are sensitive data.

Currently I'm retrieving the "listen key" via the "authentication" API with the users credentials. This data is send via HTTPS to avoid clear text transmission. But in Kodi context, credentials are stored in general in clear text in the addon profile directory.

And you are right the "listen key" is the same for all networks.

Your request impacts wider parts of the code but is of course manageable. I'll think about a solution and put this onto the agenda of v0.4.0!

**Comment by ssapalski** [comment]
I've just released v0.4.0 which includes your request.

In the addon settings you have to set "login with username/password" to false and provide than under 'listen key' your key. If your key is valid gets verified if you start a channel.

**Comment by YAMLcase** [comment]
I just got a chance to try out your changes and it works flawlessly.  Thank you for being so receptive and responsive!  I only hope other plugin authors will embrace the API key methodology as this is a much better way of integration.
