### ISSUE TITLE
0.5.1 and 0.6.0 not working?

### ISSUE THREAD

**Issue by ZipoBibrok** [ssapalski/plugin.audio.addict#11]
The addon is not working for me anymore on various Kodi installations (Android, Windows, Linux, CoreELEC/LibreELEC):

16:16:22.604 T:3916428144   DEBUG: StartScript - calling plugin AudioAddict('plugin://plugin.audio.addict/','56','','resume:false')
16:16:22.605 T:2899301232   DEBUG: Thread LanguageInvoker start, auto delete: false
16:16:22.605 T:2899301232    INFO: initializing python engine.
16:16:22.605 T:2899301232   DEBUG: CPythonInvoker(72, /storage/.kodi/addons/plugin.audio.addict/addon.py): start processing
16:16:22.637 T:2899301232   DEBUG: -->Python Interpreter Initialized<--
16:16:22.637 T:2899301232   DEBUG: CPythonInvoker(72, /storage/.kodi/addons/plugin.audio.addict/addon.py): the source file to load is "/storage/.kodi/addons/plugin.audio.addict/addon.py"
16:16:22.638 T:2899301232   DEBUG: CPythonInvoker(72, /storage/.kodi/addons/plugin.audio.addict/addon.py): setting the Python path to /storage/.kodi/addons/plugin.audio.addict:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
16:16:22.638 T:2899301232   DEBUG: CPythonInvoker(72, /storage/.kodi/addons/plugin.audio.addict/addon.py): entering source directory /storage/.kodi/addons/plugin.audio.addict
16:16:22.638 T:2899301232   DEBUG: CPythonInvoker(72, /storage/.kodi/addons/plugin.audio.addict/addon.py): instantiating addon using automatically obtained id of "plugin.audio.addict" dependent on version 2.20.0 of the xbmc.python api
16:16:22.654 T:2899301232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'audioaddict' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.addict/addon.py", line 74, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.audio.addict/addon.py", line 70, in main
                                                audioaddict.run_addon(addon_url, addon_handle, addon_args)
                                            NameError: global name 'audioaddict' is not defined
                                            -->End of Python script error report<--
16:16:22.655 T:2899301232   DEBUG: onExecutionDone(72, /storage/.kodi/addons/plugin.audio.addict/addon.py)
16:16:22.658 T:2899301232    INFO: Python interpreter stopped
16:16:22.658 T:2899301232   DEBUG: Thread LanguageInvoker 2899301232 terminating
16:16:22.665 T:3916428144   ERROR: GetDirectory - Error getting plugin://plugin.audio.addict/
16:16:22.666 T:3916428144   DEBUG: Thread waiting 3916428144 terminating
16:16:22.666 T:4091905424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.addict/) failed

Any ideas how to fix this?

**Comment by ssapalski** [comment]
Which Kodi version do you use?

This issue is a bit different as what was reported in the Kodi forum, there the import of the audioaddict module failed, here it seems to be successful but for some reason isn't recognized at the time of use.

I try to reproduce it with the Kodi version you use. If not possible, I will ask for more information which could help to identify the root cause.

**Comment by ZipoBibrok** [comment]
Hi,

Kodi versions on all these platforms are all alpha - 18 v3.
I guess it has something to do with python migration.
I am at your disposal for any further information, which might help.

Thank you in advance!

P.S. I am a "premium" user on AudioAddict service, just for final clarification, if that matters...

**Comment by ssapalski** [comment]
I was able to reproduce it and a fix + new release is out. You can download v0.6.1 from the [releases](https://github.com/ssapalski/plugin.audio.addict/releases) page. Please rename the downloaded archive to plugin.audio.addict.zip before installing it!
