### ISSUE TITLE
Adding channels via Chorus (webui) doesn't show channel title or image in playlist

### ISSUE THREAD

**Issue by axelsimon** [ssapalski/plugin.audio.addict#6]
Hi,
As stated in the title, adding channels via Chorus (official Kodi webui) doesn't show channel title or art in the Kodi playlist displayed by Chorus.

This may be a Chorus bug, but given there was a similar one opened about Yatse (issue #4) so I thought it was worth mentioning this one.

Thanks!

**Comment by axelsimon** [comment]
Screenshot to illustrate:
![screenshot from 2017-09-26 14-20-25](https://user-images.githubusercontent.com/1172256/30860115-4f7eb2f0-a2c6-11e7-8808-86c81cbea297.png)

(first item is an item added by the [Radio](http://kodi.wiki/view/Add-on:Radio) plugin, then the next three are items added by the Audio Addict plugin: the DI.fm House, Drum and Bass and Glitch Hop channels as you, well, *can't* tell 😉)

**Comment by ssapalski** [comment]
I'm not familiar with Chorus so far but I will look into it.
Unfortunately this ticket has currently no high priority for me due to the lack of time at the moment I can spend into this project. I'm sorry for that but I guarantee that I will look into it as soon as it fits.

**Comment by ssapalski** [comment]
Yesterday finally I was looking at it, with chorus2 (default web ui) I don't see any issues. But you are still using chorus1?

**Comment by ssapalski** [comment]
I made some more tests with latest Kodi/Chorus and I see in the playlist the song title + channel icon.
For me this looks like a bug in an older Kodi+Chorus version!

**Comment by axelsimon** [comment]
Hi, sorry for the slow reply. I was using Chorus2 but the underlying system was a several times upgraded Kodibunty (xbmcbuntu actually). I'm going to reinstall the whole thing soon, if I see the issue I'll reopen but otherwise it's completely fair to close it.

**Comment by ssapalski** [comment]
If you can reproduce it with a recent Kodi/Chorus version than give me please more information:
- Kodi version
- Chorus2 version

I will analyze it if the problem still persists and you can reopen this issue!
